[windows]
10.21.1.87

ansible_user: Pranay
ansible_password: "ThomsonReuters@1711"
ansible_connection: winrm 
ansible_winrm_transport: ntlm 
ansible_port: 5985
ansible_winrm_server_cert_validation: ignore 
